import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BookOpen, AlertTriangle, Wrench, type LucideIcon } from "lucide-react";
import { SummarySection } from "./SummarySection";

interface Props {
  summary: string | null;
}

interface Section {
  title: string;
  slug: string;
  content: string;
  icon: LucideIcon;
  iconClass: string;
}

const SECTION_META: Record<string, { slug: string; icon: LucideIcon; iconClass: string }> = {
  "repository overview": { slug: "overview",        icon: BookOpen,      iconClass: "text-blue-500"  },
  "key findings":        { slug: "findings",        icon: AlertTriangle, iconClass: "text-red-500"   },
  "recommendations":     { slug: "recommendations", icon: Wrench,        iconClass: "text-amber-500" },
};

function getMeta(title: string) {
  const key = Object.keys(SECTION_META).find(k => title.toLowerCase().includes(k));
  return key ? SECTION_META[key] : {
    slug: title.toLowerCase().replace(/\s+/g, "-"),
    icon: BookOpen,
    iconClass: "text-muted-foreground",
  };
}

function parseSections(markdown: string): Section[] {
  const lines = markdown.split("\n");
  const sections: Section[] = [];
  let currentTitle = "";
  let currentLines: string[] = [];

  for (const line of lines) {
    const headingMatch = line.match(/^#{1,2}\s+(.+)/);
    if (headingMatch) {
      if (currentTitle) {
        const meta = getMeta(currentTitle);
        sections.push({ title: currentTitle, content: currentLines.join("\n").trim(), ...meta });
        currentLines = [];
      }
      currentTitle = headingMatch[1].replace(/^\d+\.\s*/, "").trim();
    } else {
      currentLines.push(line);
    }
  }

  if (currentTitle) {
    const meta = getMeta(currentTitle);
    sections.push({ title: currentTitle, content: currentLines.join("\n").trim(), ...meta });
  }

  return sections;
}

export default function SummaryPanel({ summary }: Props) {
  if (!summary) return null;

  const sections = parseSections(summary);
  if (sections.length === 0) return null;

  const defaultTab = sections[0]?.slug ?? "overview";

  return (
    <Card className="w-full mb-4">
      <CardHeader className="pb-3">
        <CardTitle className="text-xs font-medium">AI summary</CardTitle>
        <CardDescription className="text-xs text-muted-foreground">
          Architectural analysis generated by AI based on your repository metrics.
        </CardDescription>
      </CardHeader>
      <CardContent className="pt-0">
        <Tabs defaultValue={defaultTab}>
          <TabsList className="w-full h-auto flex-wrap justify-start gap-1 bg-transparent p-0 mb-4">
            {sections.map(section => {
              const Icon = section.icon;
              return (
                <TabsTrigger
                  key={section.slug}
                  value={section.slug}
                  className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-md border border-transparent data-[state=active]:border-border data-[state=active]:bg-muted"
                >
                  <Icon className={`w-3 h-3 ${section.iconClass}`} />
                  {section.title}
                </TabsTrigger>
              );
            })}
          </TabsList>

          {sections.map(section => (
            <TabsContent
              key={section.slug}
              value={section.slug}
              className="mt-0 focus-visible:outline-none"
            >
              <SummarySection
                title={section.title}
                content={section.content}
                index={0}
              />
            </TabsContent>
          ))}
        </Tabs>
      </CardContent>
    </Card>
  );
}